version: '2.0'

services:

  # Meteor
  # Data visualizations
  meteor:
    build:
      context: ./datavizplatform-meteor
      dockerfile: Dockerfile-meteor
    volumes:
      - ./datavizplatform-meteor/app:/home/meteoruser/app
    depends_on:
      - mongo
      - webserver
    links:
      - mongo
    ports:
      - 3000:3000
    environment:
      - "MONGO_URL=mongodb://mongo:27017/meteor"

  # Mongo
  # Shared db between data visualizations and analyses
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data
    ports:
      - '27017:27017'
      
  # Airflow
  # Data analyses
  # Copied and modified from the submodule datavizplatform-airflow
  redis:
    image: 'redis:3.2.7'

  postgres:
    build:
      context: ./datavizplatform-airflow
      dockerfile: Dockerfile-postgres

  webserver:
    build:
      context: ./datavizplatform-airflow
      dockerfile: Dockerfile-airflow
    depends_on:
        - postgres
        - redis
        - mongo
    env_file:
        - ./datavizplatform-airflow/environment.env
    volumes:
        - ./datavizplatform-airflow/dags:/usr/local/airflow/dags
    ports:
        - "8080:8080"
    command: webserver

  flower:
    build:
      context: ./datavizplatform-airflow
      dockerfile: Dockerfile-airflow
    depends_on:
        - redis
        - webserver
    env_file:
        - ./datavizplatform-airflow/environment.env
    ports:
        - "5555:5555"
    command: flower

  scheduler:
    build:
      context: ./datavizplatform-airflow
      dockerfile: Dockerfile-airflow
    depends_on:
        - webserver
    volumes:
        - ./datavizplatform-airflow/dags:/usr/local/airflow/dags
    env_file:
        - ./datavizplatform-airflow/environment.env
    command: scheduler

  worker:
    build:
      context: ./datavizplatform-airflow
      dockerfile: Dockerfile-airflow
    depends_on:
        - scheduler
        - webserver
    volumes:
        - ./datavizplatform-airflow/dags:/usr/local/airflow/dags
    env_file:
        - ./datavizplatform-airflow/environment.env
    command: worker

volumes:
  mongo:
  postgres:
  redis:
