version: '2.0'

services:

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data
    ports:
      - '27017:27017'

  airflow:
   build:
      context: ./datavizplatform-airflow
   volumes:
      - ./datavizplatform-airflow/
   command:
      - ./docker-compose -f docker-compose-celery.yml up --build

  meteor:
    build:
      context: ./datavizplatform-meteor
      dockerfile: Dockerfile
    volumes:
      - ./datavizplatform-meteor/app:/home/meteoruser/app
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3000:3000
    environment:
      - "MONGO_URL=mongodb://mongo:27017/meteor"

volumes:
  mongo:
