version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        env_file:
            - ./environment.env

    webserver:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
            - postgres
            - redis
        env_file:
            - ./environment.env
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: puckel/docker-airflow:1.8.1
        depends_on:
            - redis
        env_file:
            - ./environment.env
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.8.1
        depends_on:
            - webserver
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
        env_file:
            - ./environment.env
        command: scheduler

    worker:
        image: puckel/docker-airflow:1.8.1
        depends_on:
            - scheduler
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
        env_file:
            - ./environment.env
        command: worker
