version: '2.0'

services:

  # --- FRONT-END ---

  # Static homepage
  homepage:
    container_name: "DataVisPlanner-home"
    build:
      context: ./homepage
      dockerfile: Dockerfile-homepage
    ports:
      - 8000:80
    env_file:
        - ./environment.env
    environment:
      - NGINX_HOST="${NGINX_HOST}"
      - NGINX_PORT="${NGINX_PORT}"

  # Meteor
  # Data visualisations
  meteor:
    container_name: "DataVisPlanner-meteor"
    build:
      context: ./meteor/app
      # dockerfile: Dockerfile-meteor # Production
      dockerfile: Dockerfile-meteor-dev # Development
    volumes:
      - .:/meteor/app/
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3000:3000
    env_file:
        - ./environment.env
    environment:
      - MONGO_URL="${MONGO_URL_METEOR}"


  # --- DATABASES ---

  # Mongo
  # Shared db between data visualisations and analyses
  mongo:
    container_name: "DataVisPlanner-mongo"
    image: mongo:latest
    hostname: mongodb
    volumes:
      - mongo:/data
    ports:
      - 27017:27017

  # Mongo UI admin
  mongoui:
    container_name: "DataVisPlanner-mongo-ui"
    image: mongoclient/mongoclient:latest
    hostname: mongoclient
    depends_on:
      - mongo
    volumes:
      - mongo:/data
    ports:
        - 3300:3000
    env_file:
        - ./environment.env
    environment:
      - MONGO_URL="${MONGO_URL_UI}"
      - MONGOCLIENT_AUTH="${MONGOCLIENT_AUTH_UI}"
      - MONGOCLIENT_USERNAME="${MONGOCLIENT_USERNAME_UI}"
      - MONGOCLIENT_PASSWORD="${MONGOCLIENT_PASSWORD_UI}"
      - MONGOCLIENT_DEFAULT_CONNECTION_URL="${MONGOCLIENT_DEFAULT_CONNECTION_URL_UI}"

  # Redis
  redis:
    container_name: "DataVisPlanner-redis"
    image: redis:3.2.7

  # PostgreSQL
  postgres:
    container_name: "DataVisPlanner-postgres"
    hostname: postgres
    build:
      context: ./airflow
      dockerfile: Dockerfile-postgres
    ports:
        - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  # PostgreSQL UI admin
  postgresui:
      container_name: "DataVisPlanner-postgres-ui"
      image: fenglc/pgadmin4
      ports:
          - 5050:5050
      links:
          - postgres
      depends_on:
        - postgres


  # --- DATA WORKFLOWS ---

  # Cloud9
  # For editing Airflow DAGs
  cloud9:
    container_name: "DataVisPlanner-cloud9"
    image: agungf/cloud9-ide
    env_file:
        - ./environment.env
    environment:
      - ROOT_PASS="${ROOT_PASS}"
      - C9_WORKSPACE="${C9_WORKSPACE}"
    depends_on:
      - webserver
    volumes_from:
      - webserver
    ports:
      - 8181:8181
      - 22

  # Airflow
  # Data analyses
  # Copied and modified from the submodule airflow

  webserver:
    container_name: "DataVisPlanner-airflow-webserver"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    depends_on:
        - postgres
        - redis
        - mongo
    restart: always
    env_file:
        - ./environment.env
    environment:
        - EXECUTOR="${EXECUTOR}"
    volumes:
        - ./airflow/data_analysis/dags:/usr/local/airflow/dags
    links:
        - mongo
        - postgres
    ports:
        - 8080:8080
    command: webserver

  flower:
    container_name: "DataVisPlanner-airflow-flower"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    restart: always
    depends_on:
        - redis
        - mongo
    env_file:
        - ./environment.env
    environment:
        - EXECUTOR="${EXECUTOR}"
    ports:
        - 5555:5555
    links:
        - mongo
        - postgres
    command: flower

  scheduler:
    container_name: "DataVisPlanner-airflow-scheduler"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    restart: always
    depends_on:
        - webserver
        - mongo
    volumes:
        - ./airflow/data_analysis/dags:/usr/local/airflow/dags
    env_file:
        - ./environment.env
    environment:
        - EXECUTOR="${EXECUTOR}"
    links:
        - mongo
        - postgres
    command: scheduler

  worker:
    container_name: "DataVisPlanner-airflow-worker"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    restart: always
    depends_on:
        - scheduler
        - mongo
    volumes:
        - ./airflow/data_analysis/dags:/usr/local/airflow/dags
    env_file:
        - ./environment.env
    environment:
        - EXECUTOR="${EXECUTOR}"
    links:
        - mongo
        - postgres
    command: worker


  # --- MANAGEMENT ---

  # Portainer
  # For managing containers
  # https://github.com/portainer/portainer-compose
  portainer:
    container_name: "DataVisPlanner-portainer"
    image: portainer/portainer
    ports:
        - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: centurylink/watchtower
    container_name: "DataVisPlanner-portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  mongo:
  postgres:
  redis:
