version: '2.0'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data
    ports:
      - '27017:27017'

  airflow:
    build:
      context: ./datavizplatform-flask
      dockerfile: Dockerfile
    volumes:
      - ./datavizplatform-flask:/home/user_python/app
    ports:
      - "8000:8000"

  meteor:
    build:
      context: ./datavizplatform-meteor
      dockerfile: Dockerfile
    volumes:
      - ./datavizplatform-meteor/app:/home/meteoruser/app
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3000:3000
    environment:
      - "MONGO_URL=mongodb://mongo:27017/meteor"

volumes:
  redis:
  mongo:
