version: '2.0'

services:

  # Static homepage
  homepage:
    container_name: "DataVisPlanner-home"
    build:
      context: ./homepage
      dockerfile: Dockerfile-homepage
    ports:
      - 8000:80
    environment:
      #- NGINX_HOST=foobar.com
      - NGINX_PORT=80

  # Meteor
  # Data visualizations
  meteor:
    container_name: "DataVisPlanner-meteor"
    build:
      context: ./meteor/app
      dockerfile: Dockerfile-meteor
    volumes:
      - .:/meteor/app/
    depends_on:
      - mongo
      - webserver
    links:
      - mongo
    ports:
      - 3000:3000
    environment:
      - "MONGO_URL=mongodb://mongo:27017/meteor"

  # Mongo
  # Shared db between data visualizations and analyses
  mongo:
    container_name: "DataVisPlanner-mongo"
    image: mongo:latest
    hostname: mongodb
    volumes:
      - mongo:/data
    ports:
      - 27017:27017

  # Mongo UI admin
  mongoui:
    container_name: "DataVisPlanner-mongo-ui"
    image: mongoclient/mongoclient:latest
    hostname: mongoclient
    depends_on:
      - mongo
    volumes:
      - mongo:/data
    ports:
        - 3300:3000
    environment:
      - "MONGO_URL=mongodb://mongo:27017"
      - "MONGOCLIENT_AUTH=true"
      - "MONGOCLIENT_USERNAME=admin"
      - "MONGOCLIENT_PASSWORD=password"
      - "MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017"

  # Cloud9
  # For editing Airflow DAGs
  cloud9:
    container_name: "DataVisPlanner-cloud9"
    image: 'agungf/cloud9-ide'
    environment:
      - ROOT_PASS=thesecrets
      - C9_WORKSPACE=/usr/local/data_analysis
    depends_on:
      - webserver
    volumes_from:
      - webserver
    ports:
      - 8181:8181
      - 22

  # Portainer
  # For managing containers
  # https://github.com/portainer/portainer-compose
  portainer:
    container_name: "DataVisPlanner-portainer"
    image: portainer/portainer
    ports:
        - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: centurylink/watchtower
    container_name: "DataVisPlanner-portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Airflow
  # Data analyses
  # Copied and modified from the submodule airflow
  redis:
    container_name: "DataVisPlanner-redis"
    image: 'redis:3.2.7'

  postgres:
    container_name: "DataVisPlanner-postgres"
    build:
      context: ./airflow
      dockerfile: Dockerfile-postgres
    depends_on:
      - webserver
      - mongo

  webserver:
    container_name: "DataVisPlanner-airflow-webserver"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    depends_on:
        - redis
        - mongo
    restart: always
    env_file:
        - ./airflow/environment.env
    environment:
        - EXECUTOR=Celery
    volumes:
        - ./airflow/data_analysis/dags:/usr/local/airflow/dags
        - ./airflow/data_analysis/:/usr/local/data_analysis
    links:
        - mongo
    ports:
        - 8080:8080
    command: webserver

  flower:
    container_name: "DataVisPlanner-airflow-flower"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    restart: always
    depends_on:
        - redis
        - mongo
    environment:
        - EXECUTOR=Celery
    ports:
        - 5555:5555
    links:
        - mongo
    command: flower

  scheduler:
    container_name: "DataVisPlanner-airflow-scheduler"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    restart: always
    depends_on:
        - webserver
        - mongo
    volumes:
        - ./airflow/data_analysis/dags:/usr/local/airflow/dags
    env_file:
        - ./airflow/environment.env
    environment:
        - EXECUTOR=Celery
    links:
        - mongo
    command: scheduler

  worker:
    container_name: "DataVisPlanner-airflow-worker"
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    restart: always
    depends_on:
        - scheduler
        - mongo
    volumes:
        - ./airflow/data_analysis/dags:/usr/local/airflow/dags
    env_file:
        - ./airflow/environment.env
    environment:
        - EXECUTOR=Celery
    links:
        - mongo
    command: worker

volumes:
  mongo:
  postgres:
  redis:
