version: '2.0'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build:
      context: ./flask-celery-example
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - "app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - ./flask-celery-example:/flask-celery-example
    ports:
      - "8000:8000"

  celery:
    build:
      context: ./flask-celery-example
      dockerfile: Dockerfile
    command: celery worker -A app.celery --loglevel=info
    tty: true
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - ./flask-celery-example:/flask-celery-example
    depends_on:
      - redis

  meteor:
    build:
      context: ./python_meteor
      dockerfile: Dockerfile
    command: meteor --allow-superuser
    volumes:
      - ./python_meteor:/meteor
    env_file:
      .env
    ports:
      - 3000:3000
      - 3001:3001


volumes:
  redis:
