version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build:
      context: ./flask-celery-example
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - "app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - ./flask-celery-example:/flask-celery-example
    ports:
      - "8000:8000"

  celery:
    build:
      context: ./flask-celery-example
      dockerfile: Dockerfile
    command: celery worker -A app.celery --loglevel=info
    tty: true
    env_file:
      - '.env'
    volumes:
      - ./flask-celery-example:/flask-celery-example
    depends_on:
      - redis

volumes:
  redis:
